name: rooms
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-262.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_screenutil: ^5.8.4
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  dio: ^5.3.2
  get_it:
  flutter_styled_toast:
  fluttertoast: ^8.2.2
  internet_connection_checker: ^1.0.0+1
  image_picker: ^1.0.2
  path:
  file_picker:
  http:
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0
  flutter_svg:
  pinput: ^3.0.0
  flutter_secure_storage: ^8.0.0


dev_dependencies:
  bloc_test:
  mockito:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf

